sudo: required
dist: trusty
language: python

# Test all branches
# branches:
#   only:
#   - master
#   - /^devel.*$/

matrix:
  include:
  - python: 2.7
  - python: 3.5

before_install:
  # required for `git clone git@github.com:Avsecz/genomelake.git`
  # https://github.com/alrra/travis-scripts/blob/master/doc/github-deploy-keys.md
- |
     $(npm bin)/set-up-ssh --key "$encrypted_27b2060facfe_key" \
                           --iv "$encrypted_27b2060facfe_iv" \
                           --path-encrypted-key ".travis/github_deploy_key.enc"

install:
# setup conda
# Used from https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a


# test-environment
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pandas pytest
  h5py bcolz
# HACK - added bcolz explicitly due to error in examples/extended_coda:
#   File "bcolz/carray_ext.pyx", line 1386, in bcolz.carray_ext.carray._read_meta (bcolz/carray_ext.c:20281)
#       TypeError: __init__() got an unexpected keyword argument 'quantize'
- source activate test-environment
- python --version
- pip --version

# install all the requirements
- pip install -r requirements_dev.txt

# HACK - remove it after making genomelake public
- git clone git@github.com:Avsecz/genomelake.git
- pip install cython
- pip install genomelake/

# install the repository, use tensorflow as backend by default
- pip install .
- pip install tensorflow

script:
- PYTHONPATH=$PWD:$PYTHONPATH py.test tests/
