version: 2

variables:
  update_conda: &update_conda
    run:
      name: Update conda
      command: conda update --yes conda
  install_sys_deps: &install_sys_deps
    run:
      name: install build-essential
      command: apt-get update && apt-get install -y build-essential libz-dev libcurl3-dev
  install_singularity: &install_singularity
    run:
      name: Install Singularity
      command: |
        conda install --yes -c conda-forge singularity
  install_kipoi_plugins: &install_kipoi_plugins
    run:
      name: Install kipoi plugins
      command: |
        pip install kipoi_interpret
        pip install kipoi_veff
        pip install kipoiseq
        pip install pyfaidx
        conda install --yes -c conda-forge fastparquet zarr numcodecs

  export_shortcuts: &export_shortcuts
    run:
      name: Export shortcuts 
      command: |
        # for no good reason the wrong version of pytest is choosen by default...
        echo 'export PYTEST=$(conda info --base)/envs/kipoi-env/bin/pytest' >> $BASH_ENV


  install_from_dev_requirements_py3x: &install_from_dev_requirements_py3x
    run:
      name: Install from dev-requirements-py3x.yml
      command: |
        echo 'export CI_JOB_PY_YAML="$CI_JOB_PY_YAML"' >> $BASH_ENV
        conda env create --name kipoi-env -f dev-requirements.yml
        source activate kipoi-env
        pip install -e .

  install_from_dev_requirements_py36: &install_from_dev_requirements_py36
    run:
      name: Install from dev-requirements-py36.yml
      command: |
        echo 'export CI_JOB_PY_YAML="$CI_JOB_PY_YAML"' >> $BASH_ENV
        conda env create --name kipoi-env -f dev-requirements-py36.yml
        source activate kipoi-env
        pip install -e .
  install_genomelake: &install_genomelake
    run:
      name: Install pip dependencies
      command: conda install -c bioconda genomelake 
  install_kipoi: &install_kipoi
    run:
      name: Install Kipoi
      command: pip install '.[develop,vep]'
  install_requests: &install_requests
    run:
      name: Install requirements for requests correctly
      command: pip install requests
  kipoi_ls: &kipoi_ls
    run:
      name: List kipoi packages
      command: kipoi ls
  kipoi_ls: &activate_and_kipoi_ls
    run:
      name: List kipoi packages
      command: |
        source activate kipoi-env
        kipoi ls
  # run_coveralls: &run_coveralls
  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        mkdir test-reports
        pytest --cov=kipoi/ tests/ -n 4 --no-cov-on-fail --junitxml=test-reports/junit.xml
      no_output_timeout: 15m
  activate_and_run_tests: &activate_and_run_tests
    run:
      name: Run tests
      command: |
        source activate kipoi-env
        mkdir test-reports
        $PYTEST --cov=kipoi/ tests/ -n 4 --no-cov-on-fail --junitxml=test-reports/junit.xml
      no_output_timeout: 15m
  run_coveralls: &run_coveralls
    run:
      name: run coveralls
      command: coveralls || true
  activate_and_run_coveralls: &activate_and_run_coveralls
    run:
      name: activate and run coveralls
      command: |
        source activate kipoi-env
        coveralls || true
  store_test_results: &store_test_results
    store_test_results:https://circleci.com/gh/kipoi/kipoi/2541?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
      path: test-reports
  store_test_artifacts: &store_test_artifacts
    store_artifacts:
      path: test-reports
      destination: test-reports

jobs:
  test-py36-yml:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *install_from_dev_requirements_py36
      - *export_shortcuts
      - *activate_and_kipoi_ls
      - *activate_and_run_tests
      - *activate_and_run_coveralls
      - *store_test_results
      - *store_test_artifacts
  test-py3x-yml:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *install_from_dev_requirements_py3x
      - *export_shortcuts
      - *activate_and_kipoi_ls
      - *activate_and_run_tests
      - *activate_and_run_coveralls
      - *store_test_results
      - *store_test_artifacts

  test-py36:
    docker:
      - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *install_sys_deps
      - *update_conda
      - *install_singularity
      - *install_genomelake
      - *install_kipoi
      - *install_kipoi_plugins
      - *kipoi_ls
      - *run_tests
      - *run_coveralls
      - *store_test_results
      - *store_test_artifacts

  build-deploy-docs:
    docker:
      # - image: continuumio/miniconda3:4.5.12
      - image: continuumio/anaconda3:5.0.1
      # - image: circleci/python:3.5
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 60:0f:05:31:12:3d:bc:8b:df:9d:08:da:71:a5:43:b6
      - checkout
      - run:
          name: Install pip - Kipoi
          command: pip install -e .
      - run:
          name: Install build deps
          command: pip install nbconvert==5.4.0 tornado==5.1.1 mkdocs pydoc-markdown
      - run:
          name: Build docs
          command: |
            cd docs/
            ./render_ipynb.bash
            pydocmd build
      - run:            - test-py36
          name: Deploy docs
          command: .circleci/deploy_docs.bash
workflows:
  version: 2

  # TODO - consider running the deploy only on
  # tag commits: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
  test-n-deploy:
    jobs:
      - test-py36-yml
      - test-py3x-yml

      - build-deploy-docs:
          requires:
            - test-py36-yml
            - test-py3x-yml
          filters:
            branches:
              only:
                - master
                - test_deployment_script
